#!/bin/bash
# scripts/init-test-server.sh
# Initialize server with test user and API key for client authentication

set -e

# Configuration
SERVER_URL="${SERVER_URL:-http://localhost:3020}"
TEST_USER_EMAIL="${TEST_USER_EMAIL:-testuser@example.com}"
TEST_USER_PASSWORD="${TEST_USER_PASSWORD:-testpass123}"
TEST_USER_USERNAME="${TEST_USER_USERNAME:-testuser}"
MAX_RETRIES=30
RETRY_DELAY=2

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[Init]${NC} $1"
}

print_error() {
    echo -e "${RED}[Error]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[Success]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[Warning]${NC} $1"
}

# Function to wait for server to be ready
wait_for_server() {
    print_status "Waiting for server to be ready at ${SERVER_URL}..."
    
    for i in $(seq 1 $MAX_RETRIES); do
        if curl -f "${SERVER_URL}/health" > /dev/null 2>&1; then
            print_success "Server is ready!"
            return 0
        fi
        
        if [ $i -eq $MAX_RETRIES ]; then
            print_error "Server failed to start after $((MAX_RETRIES * RETRY_DELAY)) seconds"
            return 1
        fi
        
        echo -n "."
        sleep $RETRY_DELAY
    done
}

# Function to create test user
create_test_user() {
    print_status "Creating test user: ${TEST_USER_USERNAME}"
    
    # Register the user
    REGISTER_RESPONSE=$(curl -s -X POST "${SERVER_URL}/api/auth/register" \
        -H "Content-Type: application/json" \
        -d "{
            \"username\": \"${TEST_USER_USERNAME}\",
            \"email\": \"${TEST_USER_EMAIL}\",
            \"password\": \"${TEST_USER_PASSWORD}\"
        }")
    
    # Check if user already exists or was created
    if echo "$REGISTER_RESPONSE" | grep -q "already exists"; then
        print_warning "User already exists, proceeding with login"
    elif echo "$REGISTER_RESPONSE" | grep -q "error"; then
        print_error "Failed to create user: $REGISTER_RESPONSE"
        return 1
    else
        print_success "User created successfully"
    fi
    
    return 0
}

# Function to login and get JWT token
login_user() {
    print_status "Logging in as ${TEST_USER_USERNAME}..."
    
    LOGIN_RESPONSE=$(curl -s -X POST "${SERVER_URL}/api/auth/login" \
        -H "Content-Type: application/json" \
        -d "{
            \"username\": \"${TEST_USER_USERNAME}\",
            \"password\": \"${TEST_USER_PASSWORD}\"
        }")
    
    # Extract token from response
    JWT_TOKEN=$(echo "$LOGIN_RESPONSE" | grep -o '"token":"[^"]*' | cut -d'"' -f4)
    
    if [ -z "$JWT_TOKEN" ]; then
        print_error "Failed to get JWT token: $LOGIN_RESPONSE"
        return 1
    fi
    
    print_success "Login successful"
    echo "$JWT_TOKEN"
}

# Function to create API key
create_api_key() {
    local jwt_token=$1
    print_status "Creating API key for client..."
    
    # Create a new machine/API key
    API_KEY_RESPONSE=$(curl -s -X POST "${SERVER_URL}/api/machines" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${jwt_token}" \
        -d "{
            \"name\": \"test-client-machine\",
            \"description\": \"Test client for automated testing\"
        }")
    
    # Extract API key from response
    API_KEY=$(echo "$API_KEY_RESPONSE" | grep -o '"apiKey":"[^"]*' | cut -d'"' -f4)
    
    if [ -z "$API_KEY" ]; then
        # Try to get existing API key
        print_warning "Failed to create new API key, trying to fetch existing..."
        
        MACHINES_RESPONSE=$(curl -s -X GET "${SERVER_URL}/api/machines" \
            -H "Authorization: Bearer ${jwt_token}")
        
        # Look for test-client-machine
        API_KEY=$(echo "$MACHINES_RESPONSE" | grep -o '"name":"test-client-machine"[^}]*"apiKey":"[^"]*' | grep -o '"apiKey":"[^"]*' | cut -d'"' -f4)
        
        if [ -z "$API_KEY" ]; then
            print_error "Failed to get API key: $API_KEY_RESPONSE"
            return 1
        fi
    fi
    
    print_success "API key obtained"
    echo "$API_KEY"
}

# Function to save credentials
save_credentials() {
    local api_key=$1
    local output_file="${2:-/tmp/test-credentials.env}"
    
    print_status "Saving credentials to ${output_file}"
    
    cat > "$output_file" << EOF
# Test credentials generated by init-test-server.sh
export CLIENT_API_TOKEN="${api_key}"
export TEST_USER_EMAIL="${TEST_USER_EMAIL}"
export TEST_USER_PASSWORD="${TEST_USER_PASSWORD}"
export TEST_USER_USERNAME="${TEST_USER_USERNAME}"
export SERVER_URL="${SERVER_URL}"
EOF
    
    chmod 600 "$output_file"
    print_success "Credentials saved"
}

# Main execution
main() {
    print_status "Initializing test server..."
    
    # Wait for server
    if ! wait_for_server; then
        exit 1
    fi
    
    # Create user
    if ! create_test_user; then
        exit 1
    fi
    
    # Login
    JWT_TOKEN=$(login_user)
    if [ -z "$JWT_TOKEN" ]; then
        exit 1
    fi
    
    # For testing, we'll use the JWT token as the API key
    # In production, you'd want a separate machine token
    API_KEY="$JWT_TOKEN"
    
    # Save credentials
    save_credentials "$API_KEY" "$1"
    
    # Output the API key for use in scripts
    echo "$API_KEY"
    
    print_success "Server initialization complete!"
    print_status "Client can now connect with API token: ${API_KEY:0:20}..."
}

# Run main function
main "$@"